# Generated by Django 2.2.7 on 2019-11-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('image', models.FilePathField(verbose_name='/img')),
                ('technology', models.TextField()),
            ],
        ),
    ]
